"use client";

import { usePathname } from "next/navigation";
import { Geist, Geist_Mono, Nabla } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import { SWRProvider } from "@/providers/swr-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const hideNavbar = ["/login"].includes(pathname);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SWRProvider>
          {!hideNavbar ? (
            <div>
              <Navbar />
              <main className="pt-20 p-10 min-h-screen flex-col flex">
                {children}
              </main>
            </div>
          ) : (
            <main>{children}</main>
          )}
        </SWRProvider>
      </body>
    </html>
  );
}
